In [11]:
import pandas as pd
import numpy as np

housing_df = pd.read_csv('numeric_prop_census_isd.csv')


#changed year built to years since
def years_since(x):
  return 2026-x
yr_built_correct = housing_df['rs_prop_yr_built'].map(years_since)
print(yr_built_correct)
housing_df.insert(1, 'rs_prop_yrs_since_built',yr_built_correct)
housing_df = housing_df.drop(columns=['rs_prop_yr_built'])

#first tried fillna(0) but had bad accuracy-- replaced w mean of columns, didn't change much
#for column_name in housing_df:
  #housing_df[column_name].fillna(housing_df[column_name].mean(),inplace=True)
 
  
housing_df = housing_df.fillna(housing_df.mean())
print(housing_df.head)


#outcome column: violation_count

0         301
1         301
2         236
3         316
4         227
         ...
315288      9
315289     22
315290     20
315291     16
315292     25
Name: rs_prop_yr_built, Length: 315293, dtype: int64
<bound method NDFrame.head of         rs_prop_sam_id  rs_prop_yrs_since_built  rs_prop_yr_remod  \
0               407453                      301       2010.000000
1               407452                      301       2010.000000
2                62318                      236          0.000000
3               133181                      316          0.000000
4                73295                      227       2014.000000
...                ...                      ...               ...
315288          186426                        9          0.000000
315289           80028                       22       1523.764783
315290           27664                       20       1523.764783
315291          341536                       16       1523.764783
315292          106156                       25       1523.764783

        rs_prop_living_area  json_mhl_housing_5year  \
0                      2160                       0
1                      2160                       0
2                      2480                       0
3                      1761                       0
4                      2610                       0
...                     ...                     ...
315288                    0                       0
315289                 1610                       0
315290                 2496                       0
315291                    0                       0
315292                 1976                       0

        json_bldg_mhl_housing_5year  Housing_Vehicles_share_no_vehicles  \
0                                 0                            0.191520
1                                 0                            0.191520
2                                 0                            0.228362
3                                 0                            0.136259
4                                 0                            0.238620
...                             ...                                 ...
315288                            1                            0.209293
315289                            0                            0.418158
315290                            0                            0.136458
315291                            0                            0.245196
315292                            0                            0.155939

        Housing_LivingArrangements_household_pop  \
0                                     3657.00960
1                                     3657.00960
2                                     5791.40000
3                                     3618.00000
4                                     2926.95246
...                                          ...
315288                                4906.00000
315289                                2889.00000
315290                                2501.00000
315291                                2558.00000
315292                                2894.00000

        Housing_LivingArrangements_group_quarters  \
0                                           101.0
1                                           101.0
2                                             0.0
3                                             7.0
4                                            55.0
...                                           ...
315288                                       10.0
315289                                       30.0
315290                                      138.0
315291                                        8.0
315292                                      179.0

        Housing_LivingArrangements_avg_hh_size  ...  \
0                                     2.371602  ...
1                                     2.371602  ...
2                                     2.237790  ...
3                                     2.644737  ...
4                                     2.330376  ...
...                                        ...  ...
315288                                2.567242  ...
315289                                2.996888  ...
315290                                2.241039  ...
315291                                2.294170  ...
315292                                2.285940  ...

        Education_Attainment_share_bachelors_more  violation_count  LU_CM  \
0                                        0.728238                0      0
1                                        0.728238                0      0
2                                        0.426134                0      0
3                                        0.482840                0      0
4                                        0.568639                1      0
...                                           ...              ...    ...
315288                                   0.527149                1      1
315289                                   0.120817                0      0
315290                                   0.676357                0      0
315291                                   0.759819                0      1
315292                                   0.490880                0      0

        LU_E  LU_EA  LU_R1  LU_R2  LU_R3  LU_R4  LU_RC
0          0      0      0      1      0      0      0
1          0      0      0      1      0      0      0
2          0      0      1      0      0      0      0
3          0      0      1      0      0      0      0
4          0      0      1      0      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
315288     0      0      0      0      0      0      0
315289     0      0      1      0      0      0      0
315290     0      0      1      0      0      0      0
315291     0      0      0      0      0      0      0
315292     0      0      1      0      0      0      0

[315293 rows x 52 columns]>

In [12]:
housing_df = housing_df.drop(columns=['json_bldg_mhl_housing_5year','json_mhl_housing_5year','rs_prop_yr_remod'])

In [13]:
#total split: 64% of data to train each classification and regression, 16% to test each, and 20% to test the two-step model
X = housing_df.drop(columns=['violation_count'])
y = housing_df['violation_count']
# from sklearn.preprocessing import minmax_scale
# X = minmax_scale(X)
print(X.shape)
X = (X-X.min(axis=0))/(X.max(axis=0)-X.min(axis=0))
print(X.shape)

from sklearn.model_selection import train_test_split
X_train_total, X_test_2step, y_train_total, y_test_2step = train_test_split(X, y, test_size=0.2, random_state=42)



X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_train_total, y_train_total, test_size = 0.2, random_state=42)

#below are the training/testing data to use for classifier since we want to have it train on just 0's and 1's

X_train_cla = X_train_reg.copy()

X_test_cla = X_test_reg.copy()

y_train_cla = y_train_reg.copy()

y_test_cla = y_test_reg.copy()

#TODO drop rows with no violations for regression - get indices from y where violations are not 0 then slice X using those indices
#X_train_reg = X_train_reg[X_train_reg['violat']]


#change classifier data to only 0 or 1
def binary(x):
  if(x==0):
    return 0
  else:
    return 1

print(y_train_cla.head)
y_train_cla = y_train_cla.map(binary)
y_test_cla = y_test_cla.map(binary)

print(y_train_cla.head)


#X_train_total.shape, X_test_2step.shape, X_train_one.shape, X_test_one.shape

(315293, 48)
(315293, 48)
<bound method NDFrame.head of 253205    0
116626    0
292726    1
51576     4
153916    0
         ..
81245     0
175956    0
141474    2
239801    0
198931    7
Name: violation_count, Length: 201787, dtype: int64>
<bound method NDFrame.head of 253205    0
116626    0
292726    1
51576     1
153916    0
         ..
81245     0
175956    0
141474    1
239801    0
198931    1
Name: violation_count, Length: 201787, dtype: int64>

In [14]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train_cla, y_train_cla)
y_pred_cla = log_reg.predict(X_test_cla)

In [15]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test_cla, y_pred_cla)
cnf_matrix

array([[24066,  5995],
       [11318,  9068]])

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test_cla, y_pred_cla))

              precision    recall  f1-score   support

           0       0.68      0.80      0.74     30061
           1       0.60      0.44      0.51     20386

    accuracy                           0.66     50447
   macro avg       0.64      0.62      0.62     50447
weighted avg       0.65      0.66      0.64     50447

In [17]:
from sklearn.linear_model import LinearRegression

# Filter regression data to only include rows with violations
violation_indices_train = y_train_reg[y_train_reg > 0].index
X_train_reg_filtered = X_train_reg.loc[violation_indices_train]
y_train_reg_filtered = y_train_reg.loc[violation_indices_train]

violation_indices_test = y_test_reg[y_test_reg > 0].index
X_test_reg_filtered = X_test_reg.loc[violation_indices_test]
y_test_reg_filtered = y_test_reg.loc[violation_indices_test]

lin_reg = LinearRegression()
lin_reg.fit(X_train_reg_filtered, y_train_reg_filtered)
y_pred_reg = lin_reg.predict(X_test_reg_filtered)


from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from math import sqrt

rmse = sqrt(mean_squared_error(y_test_reg_filtered, y_pred_reg))
r2 = r2_score(y_test_reg_filtered, y_pred_reg)
mae = mean_absolute_error(y_test_reg_filtered, y_pred_reg)

print(f'RMSE: {rmse}')
print(f'R^2: {r2}')
print(f'MAE: {mae}')

RMSE: 3.308508556712606
R^2: 0.15001257276781288
MAE: 2.116269305779475

In [18]:
# two step model: use classifier to predict if there will be a violation, then use regression to predict how many if classifier predicts there will be a violation
#fit on leftover 20% of data that we haven't used for either model yet
log_reg.fit(X_train_total, y_train_total.map(binary))

# Predict on training data to identify predicted positives
train_pred_cla = log_reg.predict(X_train_total)

# Filter training data to only predicted positives for regression training
X_train_reg_filtered = X_train_total[train_pred_cla == 1]
y_train_reg_filtered = y_train_total[train_pred_cla == 1]

lin_reg.fit(X_train_reg_filtered, y_train_reg_filtered)

y_pred_2step_cla = log_reg.predict(X_test_2step)
y_pred_2step_reg = lin_reg.predict(X_test_2step)
# evaluate two step model
y_pred_2step_final = []
for i in range(len(y_pred_2step_cla)):
  if y_pred_2step_cla[i] == 0:
    y_pred_2step_final.append(0)
  else:
    y_pred_2step_final.append(y_pred_2step_reg[i])


rmse_2step = sqrt(mean_squared_error(y_test_2step, y_pred_2step_final))
r_squared_2step = r2_score(y_test_2step, y_pred_2step_final)
mae_2step = mean_absolute_error(y_test_2step, y_pred_2step_final)

print(f'Two-step model RMSE: {rmse_2step}')
print(f'Two-step model R^2: {r_squared_2step}')
print(f'Two-step model MAE: {mae_2step}')

Two-step model RMSE: 2.6245600762389287
Two-step model R^2: 0.07933437462170212
Two-step model MAE: 1.2460521572218315

In [19]:
#eval two-step with 20% left out, still with class 1 
log_reg.fit(X_train_total, y_train_total.map(binary))
lin_reg.fit(X_train_total, y_train_total)
y_pred_2step_cla = log_reg.predict(X_test_2step)
y_pred_2step_reg = lin_reg.predict(X_test_2step)

mae_2step = mean_absolute_error(y_test_2step, y_pred_2step_reg)
rmse_2step = sqrt(mean_squared_error(y_test_2step, y_pred_2step_reg))
r_squared_2step = r2_score(y_test_2step, y_pred_2step_reg)

print(f'Two-step model RMSE: {rmse_2step}')
print(f'Two-step model MAE: {mae_2step}')
print(f'Two-step model R-squared: {r_squared_2step}')

Two-step model RMSE: 2.5722275119455107
Two-step model MAE: 1.4543673910662294
Two-step model R-squared: 0.11568365969914896

In [33]:
class_coef = log_reg.coef_
reg_coef = lin_reg.coef_
# print(class_coef[0].shape)
# print(reg_coef.shape)
coef = pd.DataFrame([class_coef[0], reg_coef], index=["Classification Coef", "Regression Coef"], columns=X.columns)
coef = coef.transpose()

In [36]:
coef["classcoefabs"] = coef["Classification Coef"].abs()
coef.sort_values(by="classcoefabs", ascending=False, inplace=True)
coef.drop(columns=["classcoefabs"], inplace=True)
coef

,Classification Coef,Regression Coef
Population_Sex_female_share,-2.571485,-2.387583e+00
Population_Age_share_55_plus,2.563567,9.729838e+00
rs_prop_living_area,2.378479,5.156123e+00
Housing_Units_total,1.994119,2.911877e+00
Population_ChildrenByAge_under5,-1.597369,-2.456346e+00
Housing_LivingArrangements_group_quarters,1.507682,1.802695e+07
Population_Age_0_to_9,1.397202,-7.926808e+06
Population_Age_65_plus,-1.323808,-1.322581e+07
LU_R1,-1.314327,-5.413237e-01
Housing_LivingArrangements_household_pop,-1.246852,2.834815e+07
Population_Age_share_20_to_34,1.055019,8.811782e+00
rs_prop_yrs_since_built,-1.034013,-2.413677e+00
Population_Age_share_0_to_9,1.019493,9.244190e+00
LU_R2,-0.886289,-4.789913e-01
Population_Race_share_black_african_american,0.774536,9.424294e+00
Housing_Tenure_owner,-0.702593,-6.723193e-01
Population_Age_35_to_54,0.692791,-1.677292e+07
Population_Age_20_to_34,-0.595387,-3.930129e+07
Education_Attainment_share_bachelors_more,0.525373,-8.184121e-01
Population_Age_55_to_64,0.500390,-9.878156e+06
Housing_Vehicles_share_no_vehicles,0.481175,1.053742e+00
Population_Race_share_asian_pacific_islander,0.466202,6.158355e+00
Population_Race_share_non_white,-0.455879,-1.033457e+01
Income_Poverty_pov_rate,0.449402,-1.914959e-01
Education_Attainment_share_LT_highschool,0.415924,-6.339259e-01
LU_R3,-0.404591,-2.267851e-01
LU_EA,0.403948,-1.105164e-01
Income_Poverty_tot_pov_stat_det,0.381661,8.541489e+00
Population_Race_american_indian_alaska_native,0.359777,1.258596e+00
Housing_Units_vacancy_rate,-0.330884,5.812557e-01
Population_Age_10_to_19,-0.327856,-1.941219e+07
Labor_LaborForce_male_participation_rate,0.311392,6.827974e-01
Population_Sex_total_pop,-0.288062,3.980665e+07
Population_Race_share_hispanic_latino,0.286084,1.147858e+01
Housing_Units_units_per_acre,-0.280789,-4.778952e+00
LU_R4,-0.273427,-1.755664e-01
Labor_Commute_share_worked_from_home,-0.228830,-1.110181e-02
rs_prop_sam_id,-0.217276,2.382723e-01
LU_CM,-0.212385,-1.964883e-01
LU_E,-0.212059,5.108490e-01
Population_Density_pop_per_sq_mi,0.202250,4.147828e+00
Population_Race_other,0.197674,3.233008e+00
Population_ChildrenByAge_5_to_17,-0.125257,-3.921377e+00
Population_Race_two_plus,-0.123439,1.233681e+00
Labor_LaborForce_female_participation_rate,0.067194,-1.553686e+00
Housing_LivingArrangements_avg_hh_size,-0.061906,-2.860751e-01
Population_Nativity_share_foreign_born,-0.008892,-4.265112e-01
LU_RC,-0.004033,-8.179290e-03

In [ ]:
coef["regcoefabs"] = coef["Regression Coef"].abs()
coef.sort_values(by="regcoefabs", ascending=False, inplace=True)
coef.drop(columns=["regcoefabs"], inplace=True)
coef

,Classification Coef,Regression Coef
Population_Sex_total_pop,-0.288062,3.980665e+07
Population_Age_20_to_34,-0.595387,-3.930129e+07
Housing_LivingArrangements_household_pop,-1.246852,2.834815e+07
Population_Age_10_to_19,-0.327856,-1.941219e+07
Housing_LivingArrangements_group_quarters,1.507682,1.802695e+07
Population_Age_35_to_54,0.692791,-1.677292e+07
Population_Age_65_plus,-1.323808,-1.322581e+07
Population_Age_55_to_64,0.500390,-9.878156e+06
Population_Age_0_to_9,1.397202,-7.926808e+06
Population_Race_share_hispanic_latino,0.286084,1.147858e+01
Population_Race_share_non_white,-0.455879,-1.033457e+01
Population_Age_share_55_plus,2.563567,9.729838e+00
Population_Race_share_black_african_american,0.774536,9.424294e+00
Population_Age_share_0_to_9,1.019493,9.244190e+00
Population_Age_share_20_to_34,1.055019,8.811782e+00
Income_Poverty_tot_pov_stat_det,0.381661,8.541489e+00
Population_Race_share_asian_pacific_islander,0.466202,6.158355e+00
rs_prop_living_area,2.378479,5.156123e+00
Housing_Units_units_per_acre,-0.280789,-4.778952e+00
Population_Density_pop_per_sq_mi,0.202250,4.147828e+00
Population_ChildrenByAge_5_to_17,-0.125257,-3.921377e+00
Population_Race_other,0.197674,3.233008e+00
Housing_Units_total,1.994119,2.911877e+00
Population_ChildrenByAge_under5,-1.597369,-2.456346e+00
rs_prop_yrs_since_built,-1.034013,-2.413677e+00
Population_Sex_female_share,-2.571485,-2.387583e+00
Labor_LaborForce_female_participation_rate,0.067194,-1.553686e+00
Population_Race_american_indian_alaska_native,0.359777,1.258596e+00
Population_Race_two_plus,-0.123439,1.233681e+00
Housing_Vehicles_share_no_vehicles,0.481175,1.053742e+00
Education_Attainment_share_bachelors_more,0.525373,-8.184121e-01
Labor_LaborForce_male_participation_rate,0.311392,6.827974e-01
Housing_Tenure_owner,-0.702593,-6.723193e-01
Education_Attainment_share_LT_highschool,0.415924,-6.339259e-01
Housing_Units_vacancy_rate,-0.330884,5.812557e-01
LU_R1,-1.314327,-5.413237e-01
LU_E,-0.212059,5.108490e-01
LU_R2,-0.886289,-4.789913e-01
Population_Nativity_share_foreign_born,-0.008892,-4.265112e-01
Housing_LivingArrangements_avg_hh_size,-0.061906,-2.860751e-01
rs_prop_sam_id,-0.217276,2.382723e-01
LU_R3,-0.404591,-2.267851e-01
LU_CM,-0.212385,-1.964883e-01
Income_Poverty_pov_rate,0.449402,-1.914959e-01
LU_R4,-0.273427,-1.755664e-01
LU_EA,0.403948,-1.105164e-01
Labor_Commute_share_worked_from_home,-0.228830,-1.110181e-02
LU_RC,-0.004033,-8.179290e-03

: